development:
  sessions:
    default:
      database: projectx_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: projectx_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: projectx_production
      hosts:
        - localhost:27017
